### ISSUE TITLE
BUG Cannot connect to OBS websocket server under Fedora 41

### ISSUE THREAD

**Issue by tdcam** [StreamController/StreamController#276]
**Describe the bug**
I am trying to set up StreamController under Fedora 41. I've started OBS and enabled the WebSocket server using the default port 4455/tcp and a password. When I try to enable any of the OBS controls under StreamContoller, the web UI locks up and I have to kill it from the command line.

I see the connection to the WebSocket server in OBS Studio, but under StreamController I get an error that it can't connect to the WebSocket server and then hangs hard.

I'm running Fedora 41 up to date as of today. My desktop environment is Xfce.

**To Reproduce**
1. Make sure the WebSocket server is running in OBS Studio
2. Install StreamController 15 beta 6 via flatpak. 
3. Launch StreamController
4. Install the OBS Studio plugin
5. Try to set up changing an OBS Studio scene in StreamController
6. the UI hangs. No response to clicks, and the mouse doesn't even display on top of the app

**Expected behavior**
Change scenes in OBS studio

**Screenshots**

**Additional context**

**Comment by Eschguy** [comment]
Also an issue in GNOME. Fedora 41 6.11.8

**Comment by erinarbleizez** [comment]
Also an issue on arch with OBS version 31.0.1 installed through pacman and StreamController version 1.5.0-beta.7 installed through flatpak (regardless of the window manager used).

I have tested the websocket with netcat and I confirm the port is open. I also checked: the password didn't change and is the same between both app.

**Comment by Core447** [comment]
@erinarbleizez I can't seem to reproduce this. Can you please do the following:
1. Check that the OBS plugin is up to date (this can be done in the store)
2. Close StreamController completely using the option in the hamburger menu
3. Open StreamController from the command line using `flatpak run com.core447.StreamController`
4. Do the steps required to cause the issue
5. Post the output you can see in the terminal

**Comment by erinarbleizez** [comment]
I removed the plugin, reinstalled it, closed StreamController and launch it through CLI and here is the output when i try to change scene:

```
_get_exception_class.<locals>.Derived: 'OBSController' object has no attribute 'id'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/rpyc/core/protocol.py", line 369, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/rpyc/core/protocol.py", line 863, in _handle_call
    return obj(*args, **dict(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/backend.py", line 164, in switch_to_scene
    self.OBSController.switch_to_scene(scene)
  File "/home/erin/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/OBSController.py", line 353, in switch_to_scene
    studioModeStatus = self.get_studio_mode_enabled()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/OBSController.py", line 249, in get_studio_mode_enabled
    return self.call(requests.GetStudioModeEnabled())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erin/.var/app/com.core447.StreamController/data/plugins/com_core447_OBSPlugin/backend/.venv/lib/python3.12/site-packages/obswebsocket/core.py", line 231, in call
    message_id = str(self.id)
                     ^^^^^^^
AttributeError: 'OBSController' object has no attribute 'id'
```

**Comment by erinarbleizez** [comment]
I found the problem:

OBS is listening to all interface so even if my test with netcat worked with the LAN interface (192.168.0.XXX on default port 4455 ), StreamController was unable to connect to it through the LAN interface. Changing to the loopback interface 127.0.0.1 fixed the problem.

**Comment by Core447** [comment]
Great👍
